var subtitles =
[
["XRtPiFiDjmI",1,4,10,""],
["XRtPiFiDjmI",2,17,15,""],
["XRtPiFiDjmI",3,34,15,"Hmm"],
["XRtPiFiDjmI",4,50,15,"Hmm"],
["XRtPiFiDjmI",5,67,14,"Hmm"],
["XRtPiFiDjmI",6,83,15,""],
["XRtPiFiDjmI",7,100,31,"Jag behöver inte ha fina att jag får den där det är ett bra tips är välkomna tillbaka till lunch med ett nytt program varje vecka tisdag"],
["XRtPiFiDjmI",8,132,30,"Iallafall den svensktalande de 2:a får ha tråkigt helt enkelt och det är trevligt efter vi är på jakt efter det som fick oss att börja programmera en gång i tiden när vi var typ 12 och satt med bara undrar hur det blir med det egentligen"],
["XRtPiFiDjmI",9,162,21,"Finns inte att det är inte bara kul alltid när man skapar värde så saker av värde så blir det måste vara tråkiga saker ibland så är det för att vi ska orka göra mer tråkiga saker som vi kan skapa saker av värde resten av veckan"],
["XRtPiFiDjmI",10,184,6,"Jag ser att christer med oss igen vi härligt med återkommande återkommande besökande"],
["XRtPiFiDjmI",11,191,9,"Hur är läget idag var vad vara ifrån alla från göteborg här chatten förresten eller av annan från annanstans"],
["XRtPiFiDjmI",12,201,8,"Ja det är frågan det är lite intressant att veta hur länge det har hmm det är de närmast sörjande eller om det är faktiskt börjat sprida sig lite"],
["XRtPiFiDjmI",13,210,11,"Jönköping det är då du kommit en bit ut i landet fantastisk hmm det förvirrat kan man väl säga men så är det det här kommer bli det blir nog roligare när det förvirrat"],
["XRtPiFiDjmI",14,223,24,"Jess kort och vi hade ingen ström förra veckan för hmm jag tog mig en sväng i skolan så är det ju när man är barn men det är kul det så körde vi hmm"],
["XRtPiFiDjmI",15,249,3,"Hmm ska vi se om vi kan få barn jag också"],
["XRtPiFiDjmI",16,253,16,"Ja jag har gjort lite nu mellan strömmarna här ska vi säga och det är strålande och nu och jag vet att nasa för att det är från skövde eller inte är från men för tillfället befinner sig i jönköping och det är nästan värd"],
["XRtPiFiDjmI",17,270,8,"Blev det inget dead nere blev lite ledsen vi får vi får lagra du vill få ägna strömmen något för brotten arne vi håller på med"],
["XRtPiFiDjmI",18,279,30,"Hmm nu märker jag är förvirrad och det är botten arne och botten är ju där fina game ett sånt hade på nittiotalet och det enda felet med dig att det är för lite"],
["XRtPiFiDjmI",19,309,1,""],
["XRtPiFiDjmI",20,313,7,"Jag kommer funka bra men det är en bra start och sedan tycker jag att vi jobbar vidare därifrån sen om det blir bra eller om det blir"],
["XRtPiFiDjmI",21,321,30,"Vi måste träda upp diagrammet och göra roliga saker jag tror att det kan vara ganska kasst på det från början så nästa steg framöver tänker jag något i stil med att vi kommer uppskatta den här är twitch med med är game ett och så kan ni styra det lite sådär och sen så kollade vi på lite"],
["XRtPiFiDjmI",22,352,6,"Mina drömmar och ideer och sådär som jag sitter och funderar på när när jag har tråkigt vad tror du om det"],
["XRtPiFiDjmI",23,359,9,"Jess nu har ramlat eller kanske så vi vi kan väl börja kolla lite på här"],
["XRtPiFiDjmI",24,369,14,"Paris the report för botten arne på itab som supra i sverige har alla länkar du gjorde förra gången var att vi fick upp hmm klippig på skärmar just det"],
["XRtPiFiDjmI",25,384,4,"Jag klipper funkar fortfarande inte vad det är arne kom jag nu"],
["XRtPiFiDjmI",26,389,2,"Om jag tar bort arne och ta fram a nu igen"],
["XRtPiFiDjmI",27,393,15,"Den ska dyka upp där har vi den senare ja jag bara det har gjorts sedan sist var att jag flyttar lite problemet är att det faktiskt ligger där i bild i bild ja jag skulle bara styra det och vi kunde skicka lite saker"],
["XRtPiFiDjmI",28,409,18,"De har gjort den här klipper JS har vi lyfter in det är bara jag varit framme och signal r för att kunna skicka kommandon till hmm s så hmm hmm"],
["XRtPiFiDjmI",29,428,30,"Ni kanske börjar i fel ände för att få för att få det här hmm att kunna lyssna på saker så tänkte jag att jag kollar rätt mycket på sånt här gjorts hmm det inbyggt taligenkänning i windows 10 så där det här så jag tänkte att vi"],
["XRtPiFiDjmI",30,458,5,"Hmm det ser ut ungefär så här jag vet inte hur många av er har arbetat något matcher"],
["XRtPiFiDjmI",31,464,9,"De som har de känner igen de här fantastiska hmm fantastiska oj vad konstigt det här fantastiska djuret"],
["XRtPiFiDjmI",32,474,10,"Det är så mycket konstigt hemligt i askim grejen som jag tänker att det är dumt om vi säger så så jag har gjort en liten screenshot och är noterat"],
["XRtPiFiDjmI",33,485,9,"Så det man behöver är att man bör skapa en sån här cognitive services och de är givetvis hmm översatt saker till svenska jag vet inte varför de håller på så"],
["XRtPiFiDjmI",34,496,18,"Det är fortfarande så att när man installerar det här är dock ett från början att den översätter alla felmeddelanden till svenska men vill ha det innan de hade när automatiskt text översättningar som har haft folk som på allvar har suttit och översatt den till svenska"],
["XRtPiFiDjmI",35,514,30,"Snacka om hmm bortkastade gärning i livet hmm nu är det automatiskt är alltså nu man måste fortfarande gå ner och klicka borta mycket lite kul hmm lite såna från microsoft"],
["XRtPiFiDjmI",36,545,7,"Slutpunkt som det så här alltså direktöversatt endpoint vem säger slutpunkt"],
["XRtPiFiDjmI",37,552,19,"Och jag har skapat upp en sån här cognitive services resurs i västeurop datacentret för att det är om man anlägger en cd som har minst liten sig från från göteborg i alla fall man skulle kunna tro att det är något djur men hmm så är det inte är bra bra grejer"],
["XRtPiFiDjmI",38,573,9,"Och det här ska man prata instans där nyckel som var petad nånstans och så får man läsa lite också och grejer och jag fick ingen ordning på det så därför så"],
["XRtPiFiDjmI",39,584,6,"Så så så hmm leta upp ett fint exempel hmm"],
["XRtPiFiDjmI",40,591,19,"Rätt cognitus rörelsespel chester på nu innan konstig fil jag vet inte varför jag kanske längtar jag hmm s hmm och här har vi bra och grejer och den här jag då kunnat ut för att vi bara ska kunna få det här steget är väl att få saker att hmm"],
["XRtPiFiDjmI",41,612,2,"Kunde han se sa att den kan lyssna på oss"],
["XRtPiFiDjmI",42,614,0,"Right"],
["XRtPiFiDjmI",43,616,11,"Såhär har vi har dock lånat ut det här är susanne puls gången till service husbil fest på det är oftast det snabbaste sättet att lära sig saker jag kör du hittar deras sambos"],
["XRtPiFiDjmI",44,629,4,"Ä i alla fall visat sig bra senaste"],
["XRtPiFiDjmI",45,634,8,"Åren där sa nu är med och hade massa bra grejer vi kan ju testa och köra det här"],
["XRtPiFiDjmI",46,643,24,"Se vad som händer stämmer fortfarande funkar nog inte prövat det är samtidigt som jag skriver om det fortfarande kommer åt mikrofonen och här har en massa exempel på bra grejer jag tänker inte läsa alla här där jag råkar ju av en slump vet att det är alternativ B."],
["XRtPiFiDjmI",47,668,2,"Där i hmm bilderna som vi prövar v"],
["XRtPiFiDjmI",48,672,5,"Om du ska lyssna på saker så får vi se om den hmm kan tolka skulle ploppa upp här"],
["XRtPiFiDjmI",49,680,6,"Om man kollar den har faktiskt en liten liten text men det funkar ju ganska bra ut efter bookseller"],
["XRtPiFiDjmI",50,687,3,"Jag tänker att den här borde vi ju kunna"],
["XRtPiFiDjmI",51,691,6,"Sno den här koden vippa rutorna koden för det här vi ute efter okej bra"],
["XRtPiFiDjmI",52,698,6,"Så steget kanske är att vi ska få upp det som hmm automatiskt samtidigt eller jag vet inte om det stör nu men"],
["XRtPiFiDjmI",53,706,10,"Hmm följa upp det här vad är det här b nånstans du går in i program ses hmm jag inne i hmm gått snett"],
["XRtPiFiDjmI",54,717,2,"Hmm samtals"],
["XRtPiFiDjmI",55,721,1,"C sharp"],
["XRtPiFiDjmI",56,723,18,"Gått snett hmm jag vet inte varför har vi då så vi har gott nytt år jag tänker att det vill jag ha det här så hmm talat så oberoende av os och grejer som möjligt det känns smutsigt annars"],
["XRtPiFiDjmI",57,743,18,"Så det är den jag inne och rotar i va så får vi se hur långt vi kommer med det är det vet man inte så det hmm konsult IB är den här lilla prylar continue jag kunna det här är bra det är precis den är bra"],
["XRtPiFiDjmI",58,762,30,"Jag har har förberett lite här för det är så att jag behöver veta in som skribent i ni kommer ihåg det fina som är blå här skulle vilja se om vi kan hitta dem med hjälp av dig för jag har ingen aning"],
["XRtPiFiDjmI",59,792,30,"Ändå är tanken att ni inte ska komma åt vad som kan du gå in och och använda mina krediter i aktier men jag vet inte om det kommer funka jag bara läser ut den här filen för hmm det var för krångligt att göra hmm"],
["XRtPiFiDjmI",60,823,4,"Svensson och sen har jag ju då det är dyrt"],
["XRtPiFiDjmI",61,828,6,"Lagt till att den är svenskarna lyssnar på är det enda hjortdjur samhället för att det skulle funka"],
["XRtPiFiDjmI",62,835,26,"Hmm det det här framför allt är det som har hänt mycket de senaste åren att den kan svenska det kunde jag inte för det var ganska dålig fortfarande mycket bättre på engelska och det är väl inte så konstigt"],
["XRtPiFiDjmI",63,862,5,"Om du kör jag den det är därför de är där nere och ser helt paralyserat ut"],
["XRtPiFiDjmI",64,869,2,"Hmm det här vi gjorde förra gången"],
["XRtPiFiDjmI",65,874,23,"Medverkar vi har blivit frånkopplade och är det något som tar allt nu och det kanske är att jag har två stycken"],
["XRtPiFiDjmI",66,898,3,"Slussens igång kan det vara där eller vad är det som tar med kö"],
["XRtPiFiDjmI",67,904,2,"Jag säger vi fortfarande inte har lagt sig"],
["XRtPiFiDjmI",68,907,18,""],
["XRtPiFiDjmI",69,927,6,"Nu är vi tillbaka nu då"],
["XRtPiFiDjmI",70,935,13,"Jag vet inte vad det var som gjorde det där men hmm hade av internet en stund börjar jag vet inte vad vi var när den fick för sig att sluta men övergång och vi hoppas att det funkar"],
["XRtPiFiDjmI",71,950,16,"Än är det kan vara två vs u och det är ju ganska dyrt vi hmm vi har vårt exempel på hmm it SS och vi har vårat exempel på internet exempel vara"],
["XRtPiFiDjmI",72,967,7,"Så nu har vi då att det vi gjorde förra gången var ju att vi bara fulare in klippig IN"],
["XRtPiFiDjmI",73,975,1,"Jag skulle fräs här"],
["XRtPiFiDjmI",74,978,8,"Där vi bara tar emot kommandon till exempel att de ska kunna prata och sedan så gjorde vi en"],
["XRtPiFiDjmI",75,987,3,"Än en hmm en hub och så en liten"],
["XRtPiFiDjmI",76,992,3,"Litet sätt att skicka kommandon via signaler"],
["XRtPiFiDjmI",77,996,6,"Hmm är det något som går att se på"],
["XRtPiFiDjmI",78,1006,7,"Grymt grymt att se att det är på håret att den lyckas en kalle här så vi får hålla i alla hattar"],
["XRtPiFiDjmI",79,1014,30,"Hmm nu ska vi sjunga in det här person kommit till service hittar på vi låser fast den kanske och eftersom vi kör det här det här fina gemet i hmm dockor så så är det lite lurigt för dock är det ju lite tänkte att jag ska ska avskärma oss från helst oavsett och vi behöver komma åt mikrofonen och mikrofoner den sitter ju i själva den fysiska datorn här"],
["XRtPiFiDjmI",80,1044,31,"Det är inte riktigt men att så och jag jag har forskat lite där och tydligaste går det att få vårda mikrofonen och man kör en linux container i en lindex höst men har inte hittat något sätt hur man gör där i windows kör en liknande så vi kan göra det"],
["XRtPiFiDjmI",81,1076,8,"Sedan separerad från själva in på utbyten och det är ändå ganska lätt att va så jag tänkte att vi får sjunga in själva hmm"],
["XRtPiFiDjmI",82,1085,18,"Tal styrningen så där i ett eget projekt och sen så så tar vi och hmm göra någon form av interface för det är så att vi har signaler eller något annat parti eller någonting hmm appen kan skicka in"],
["XRtPiFiDjmI",83,1104,17,"Allt som sägs genom det borde väl vara enkelt tänker jag IS hmm då ska vi se då vill jag ha ett konsulat se fyrkant jättebra"],
["XRtPiFiDjmI",84,1123,6,"Kan sola vätskan är den ska ligga i botten av det är jättebra men vad ska du med det till hmm"],
["XRtPiFiDjmI",85,1131,4,"Arne listorna när jag har egentligen bara göra det om det här skulle bara"],
["XRtPiFiDjmI",86,1136,10,"Lyssna lite på mikrofonen och skicka vidare det som sägs bollar lite vi körde så där jätte gott var man ska äta mig prophon hmm"],
["XRtPiFiDjmI",87,1147,6,"s trupper eller så där blir bra eller kanske bygga brandet ganska bra namn under temat kommer bli kul"],
["XRtPiFiDjmI",88,1154,2,"Arne byggnader"],
["XRtPiFiDjmI",89,1158,5,"Jag blir helt värdelösa när man ska komma ihåg vad sakerna gör men det är ju kul"],
["XRtPiFiDjmI",90,1164,2,"Tycker jag i alla fall men"],
["XRtPiFiDjmI",91,1167,1,"Byggnader hmm"],
["XRtPiFiDjmI",92,1169,2,"Bara blir bra det kanske är det bra"],
["XRtPiFiDjmI",93,1173,3,"Vi vi kör på det"],
["XRtPiFiDjmI",94,1177,2,"Sju dåligt nej men det är bra"],
["XRtPiFiDjmI",95,1182,25,"Ska vi säga hmm JS och då skulle vi få in den här hmm ska försöka återskapa det här lyssna och spotta ut på skärmen och då tror jag att det måste vara någon form av hmm ska vi se någon form av"],
["XRtPiFiDjmI",96,1208,12,"Hmm installering verkligen inte hur bra är lite borde heta någonting i hmm kognitiv så skulle jag kunna fuska se vad 2:a har"],
["XRtPiFiDjmI",97,1222,4,"Hmm det kanske bäst att göra det i"]
]
